// <auto-generated />
using DbAccessLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbAccessLibrary.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220425163802_addSomeCoins")]
    partial class addSomeCoins
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbAccessLibrary.Models.CryptoOpenPrices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoinName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OpenPrices");
                });

            modelBuilder.Entity("DbAccessLibrary.Models.UserBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Atom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Axs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bitcoin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Dogecoin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Etherium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Litecoin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Luna")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Solana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Usdt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Xrp")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("UserBalance");
                });
#pragma warning restore 612, 618
        }
    }
}
